// workspace/apps/passx/src/components/passx/AmbientBackground.tsx
import { motion } from "framer-motion";

export function AmbientBackground() {
  return (
    <div className="fixed inset-0 -z-10 overflow-hidden">
      <motion.div
        className="ambient-orb"
        style={{ background: "var(--brand)", width: 600, height: 600, top: -200, left: -150 }}
        animate={{ x: [0, 80, 0], y: [0, 40, 0] }}
        transition={{ duration: 18, repeat: Infinity, ease: "easeInOut" }}
      />
      <motion.div
        className="ambient-orb"
        style={{ background: "var(--brand)", width: 500, height: 500, bottom: -180, right: -120, opacity: 0.3 }}
        animate={{ x: [0, -60, 0], y: [0, -30, 0] }}
        transition={{ duration: 22, repeat: Infinity, ease: "easeInOut" }}
      />
      <DoodleSvg />
    </div>
  );
}

function DoodleSvg() {
  return (
    <svg className="absolute inset-0 h-full w-full opacity-[0.06]" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
          <path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" strokeWidth="0.5" />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#grid)" />
    </svg>
  );
}

// src/app/features/passx/components/ambient-background/ambient-background.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-passx-ambient-background',
  standalone: true,
  templateUrl: './ambient-background.component.html',
  styleUrl: './ambient-background.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AmbientBackgroundComponent {}

<div class="ambient" aria-hidden="true">
  <div class="ambient-orb orb-one"></div>
  <div class="ambient-orb orb-two"></div>
  <svg class="doodle" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <pattern id="passx-grid" width="40" height="40" patternUnits="userSpaceOnUse">
        <path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" stroke-width="0.5" />
      </pattern>
    </defs>
    <rect width="100%" height="100%" fill="url(#passx-grid)" />
  </svg>
</div>
